{
"sites":[
//{"key": "T4a","name": " T4聚合","type": 4,"api": "https://t4.secan.icu/vod?sites=all&ali_token=4acb3ad2f2254ba1b566279f7cd98ba3&timeout=5","searchable": 1,"quickSearch": 1,"filterable": 1},
 //==================================js版======================================================================================================================================================================================================

{"key": "drpy_js_独播库","name": " 独播库[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/独播库.js"},
{"key": "drpy_js_追剧达人","name": " 追剧达人[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/追剧达人.js"},
{"key": "drpy_js_1080P","name": " 1080P[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/1080P.js"}
{"key": "drpy_js_利丽娅电影","name": " 利丽娅电影[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/利丽娅电影.js"},
{"key": "drpy_js_539影院","name": " 539影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/539影院.js"},
{"key": "drpy_js_首播影院","name": " 首播影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/首播影院.js"},
{"key": "drpy_js_l0l","name": " l0l[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/l0l.js"},
{"key": "drpy_js_我爱跟剧","name": " 我爱跟剧[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/我爱跟剧.js"},
{"key": "drpy_js_干饭影视","name": " 干饭影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/干饭影视.js"},
{"key": "drpy_js_喵喵","name": " 喵喵[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/喵喵.js"},
{"key": "drpy_js_万能影视","name": " 万能影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/万能影视.js"},
{"key": "drpy_js_在线之家","name": " 在线之家[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/在线之家.js"},
{"key": "drpy_js_真不卡","name": " 真不卡[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/真不卡.js"},
{"key": "drpy_js_追剧喵","name": " 追剧喵[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/追剧喵.js"},
{"key": "drpy_js_秋霞","name": " 秋霞影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/秋霞.js"}, 
{"key": "drpy_js_MXONE","name": " MXONE[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/MXONE.js"},
{"key": "drpy_js_短视频","name": " 短视频[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/短视频.js"},
{"key": "drpy_js_两个BT","name": " 两个BT[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/两个BT.js"},
{"key": "drpy_js_胖虎影视","name": " 胖虎影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/胖虎影视.js"},
{"key": "drpy_js_麦豆","name": " 麦豆影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/麦豆.js"},
{"key": "drpy_js_31看影院","name": " 31看影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/31看影院.js"},
{"key": "drpy_js_小宝影视","name": " 小宝影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/小宝影视.js"},
{"key": "drpy_js_低端影视","name": " 低端影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/ddys.js"},
{"key": "drpy_js_JustLive","name": " JustLive[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/JustLive.js"},
{"key": "drpy_js_厂长资源","name": " 厂长资源[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/厂长资源.js"},
{"key": "drpy_js_来看点播","name": " 来看点播[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/来看点播.js"},
{"key": "drpy_js_看看电影","name": " 看看电影[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/看看电影.js"},
{"key": "drpy_js_霹雳影视","name": " 霹雳影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/霹雳影视.js"},
{"key": "drpy_js_落攻阁影视","name": " 落攻阁影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/落攻阁影视.js"},
{"key": "drpy_js_趣享星趣","name": " 趣享星趣[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/趣享星趣.js"},
{"key": "drpy_js_子子影视","name": " 子子影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/子子影视.js"},
{"key": "drpy_js_皮皮泡","name": " 皮皮泡[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/皮皮泡.js"},
{"key": "drpy_js_七小时影院","name": " 七小时影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/七小时影院.js"},
{"key": "drpy_js_番茄影视","name": " 番茄影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/番茄影视.js"},
{"key": "drpy_js_看视界","name": " 看视界[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/看视界.js"},
{"key": "drpy_js_酷云77","name": " 酷云77[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/酷云77.js"},
{"key": "drpy_js_牛马TV","name": " 牛马TV[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/牛马TV.js"},
{"key": "drpy_js_夜空","name": " 夜空[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/夜空.js"},
{"key": "drpy_js_影视工厂","name": " 影视工厂[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/影视工厂.js"},
	//
	{"key": "drpy_js_vip影院","name": " 🎑vip影院[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/vip影院.js"},
	{"key": "drpy_js_百忙无果","name": " 🎑百忙无果[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/百忙无果.js"},
	{"key": "drpy_js_大米星球","name": " 🎑大米星球[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/大米星球.js"},
	{"key": "drpy_js_番茄影视","name": " 🎑番茄影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/番茄影视.js"},
	{"key": "drpy_js_看视界","name": " 🎑看视界[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/看视界.js"},
	{"key": "drpy_js_酷云77","name": " 🎑酷云77[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/酷云77.js"},
	{"key": "drpy_js_牛马TV","name": " 🎑牛马TV[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/牛马TV.js"},
	{"key": "drpy_js_夜空","name": " 🎑夜空[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/夜空.js"},
	{"key": "drpy_js_影视工厂","name": " 🎑影视工厂[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/影视工厂.js"},
	//{"key": "drpy_js_TV云播","name": " 🎑TV云播[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/TV云播.js"},
	//{"key": "drpy_js_爱看电影","name": " 🎑爱看电影[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/爱看电影.js"},
	//{"key": "drpy_js_爱看影视","name": " 🎑爱看影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/爱看影视.js"},
	//{"key": "drpy_js_天空影视","name": " 🎑天空影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/天空影视.js"},
	//{"key": "drpy_js_TV蜂","name": " 🎑TV蜂[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/TV蜂.js"}, 
        //{"key": "drpy_js_新视觉影视","name": " 🎑新视觉影视[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/新视觉影视.js"},
	//{"key": "drpy_js_小猫咪","name": " 🎑小猫咪[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/小猫咪.js"},
	//{"key": "drpy_js_猫了个咪","name": " 🎑猫了个咪[DRPY]","type": 3,"api": "https://github.com/heroaku/TVboxo/raw/main/libs/drpy.min.js","ext": "https://github.com/heroaku/TVboxo/raw/main/Js/猫了个咪.js"},

{"key": "drpy_js_360影视","name": " 360影视┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/360影视.js"},
{"key": "drpy_js_555影视","name": " 555影视┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/555影视.js"},
{"key": "drpy_js_1080P","name": " 1080P┃DRPY","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/1080P.js"},
{"key": "drpy_js_AnFuns","name": " AnFuns┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/AnFuns.js"},
{"key": "drpy_js_007影视","name": " 007影视┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/007影视.js"},
{"key": "drpy_js_cokemv","name": " cokemv┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/cokemv.js"},
{"key": "drpy_js_drpy","name": " drpy┃DRPY","type": 3,"api": "      https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/CatVodSpiderJS/raw/main/dr/drpy.js"},
{"key": "drpy_js_l0l","name": " l0l┃DRPY","type": 3,"api": "        https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/l0l.js"},
{"key": "drpy_js_LIBVIO","name": " LIBVIO┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/LIBVIO.js"},
{"key": "drpy_js_vip影院","name": " vip影院┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/vip影院.js"},
{"key": "drpy_js_百忙无果","name": " 百忙无果┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/百忙无果.js"},
{"key": "drpy_js_菜狗","name": " 菜狗┃DRPY","type": 3,"api": "       https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/菜狗.js"},
{"key": "drpy_js_大米星球","name": " 大米星球┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/大米星球.js"},
{"key": "drpy_js_番茄影视","name": " 番茄影视┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/番茄影视.js"},
{"key": "drpy_js_干饭影视","name": " 干饭影视┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/干饭影视.js"},
{"key": "drpy_js_瓜皮TV","name": " 瓜皮TV┃DRPY","type": 3,"api": "   https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/瓜皮TV.js"},
{"key": "drpy_js_剧白白","name": " 剧白白┃DRPY","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/剧白白.js"},
{"key": "drpy_js_看视界","name": " 看视界┃DRPY","type": 3,"api": "   https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/看视界.js"},
{"key": "drpy_js_库马伊","name": " 库马伊┃DRPY┃","type": 3,"api": "   https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/库马伊.js"},
{"key": "drpy_js_酷云77","name": " 酷云77┃DRPY","type": 3,"api": "   https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/酷云77.js"},
{"key": "drpy_js_蓝光影院","name": " 蓝光影院┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/蓝光影院.js"},
{"key": "drpy_js_蓝莓影视","name": " 蓝莓影视┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/蓝莓影视.js"},
{"key": "drpy_js_凌云影视","name": " 凌云影视┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/凌云影视.js"},
{"key": "drpy_js_猫了个咪","name": " 猫了个咪┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/猫了个咪.js"},
{"key": "drpy_js_喵喵","name": " 喵喵┃DRPY","type": 3,"api": "       https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/喵喵.js"},
{"key": "drpy_js_模板","name": " 模板┃DRPY","type": 3,"api": "       https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/模板.js"},
{"key": "drpy_js_莫扎兔","name": " 莫扎兔┃DRPY","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/莫扎兔.js"},
{"key": "drpy_js_牛马TV","name": " 牛马TV┃DRPY","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/牛马TV.js"},
{"key": "drpy_js_奇优影院","name": " 奇优影院┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/奇优影院.js"},
{"key": "drpy_js_奇珍异兽","name": " 奇珍异兽┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/奇珍异兽.js"},
{"key": "drpy_js_人人影视","name": " 人人影视┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/人人影视.js"},
{"key": "drpy_js_腾云驾雾","name": " 腾云驾雾┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/腾云驾雾.js"},
{"key": "drpy_js_兔小贝","name": " 兔小贝┃DRPY","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/兔小贝.js"},
{"key": "drpy_js_万能影视","name": " 万能影视┃DRPY","type": 3,"api": " https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/万能影视.js"},
{"key": "drpy_js_小猫咪","name": " 小猫咪[DRPY]","type": 3,"api": "    https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/小猫咪.js"},
{"key": "drpy_js_小强迷","name": " 小强迷[┃DRPY","type": 3,"api": "   https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/小强迷.js"},
{"key": "drpy_js_玄天","name": " 玄天┃DRPY","type": 3,"api": "      https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/玄天.js"},
{"key": "drpy_js_鸭奈飞","name": " 鸭奈飞┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/鸭奈飞.js"},
{"key": "drpy_js_夜空","name": " 夜空┃DRPY","type": 3,"api": "     https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/夜空.js"},
{"key": "drpy_js_影视工厂","name": " 影视工厂┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/影视工厂.js"},
{"key": "drpy_js_优酷","name": " 优酷┃DRPY","type": 3,"api": "      https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/优酷.js"},
{"key": "drpy_js_在线之家","name": " 在线之家┃DRPY","type": 3,"api":" https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/在线之家.js"},
{"key": "drpy_js_真不卡","name": " 真不卡┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/真不卡.js"},
{"key": "drpy_js_追剧喵","name": " 追剧喵┃DRPY","type": 3,"api": "  https://github.com/heroaku/CatVodSpiderJS/raw/main/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/追剧喵.js"},
{"key": "drpy_js_360影视_2","name": " 360影视┃DRPY2","type": 3,"api": " https://github.com/heroaku/TVboxo/raw/main/drpy/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/360影视.js"},
{"key": "drpy_js_555影视_2","name": " 555影视[DRPY]2","type": 3,"api": " https://github.com/heroaku/TVboxo/raw/main/drpy/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/555影视.js"},
{"key": "drpy_js_1080P_2","name": " 1080P┃DRPY2","type": 3,"api": "  https://github.com/heroaku/TVboxo/raw/main/drpy/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/1080P.js"},
{"key": "drpy_js_AnFunsC_2","name": " AnFuns┃DRPY2","type": 3,"api": " https://github.com/heroaku/TVboxo/raw/main/drpy/drpy.js","ext": " https://github.com/heroaku/TVboxo/raw/main/Js/AnFuns.js"}
],
"spider":"https://notabug.org/qizhen15800/My9394/raw/master/jar/drpy.jar",
"lives": [{"group": "redirect","channels": [{"name": "redirect","urls": ["proxy://do=live&type=txt&ext=aHR0cHM6Ly9hZ2l0LmFpL3FpMTY5L015OTM5NC9yYXcvYnJhbmNoL21hc3Rlci9UVi9saXZlLnR4dA=="]}]}],
"rules" : [{"host" : "*","rule" : ["douyinvod.com","/video/tos/cn/"]},{"host" : "*","rule" : ["default.365yg.com","/video/tos/cn/"]},{"host" : "*","rule" : ["/m3u8.php","path="]},{"host" : "zjmiao.com","rule" : ["play.videomiao.vip/API.php","time=","key=","path="]}],
"parses":[
{"name":"解析聚合","type":3,"url":"Demo"},
{"name":"Json并发","type":2,"url":"Parallel"},
{"name":"Json轮询","type":2,"url":"Sequence"},
{"name":"江湖小虾米","type":0,"url":"https://dm.xmflv.com:4433/?url="},
{"name":"yemu","url": "https://www.yemu.xyz/?url="},
{"name":"dbapp","url": "https://dbapp.hengj.cn/rr/tg/?url="},
{"name": "8old","type": 0,"url": "http://danmu.8old.cn/vip/?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name":"free","type":0,"url":"https://h5.freejson.xyz/player/?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"ceshi","type":1,"url":"http://211.99.99.236:4567/jhjson/ceshi.php?url=","ext":{"flag":["qiyi","iqiyi","奇艺","爱奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果","xigua","西瓜","sohu","搜狐","cntv","cctv","央视","1905","m1905"]}},
{"name":"gotka","type":1,"url":"http://newjiexi.gotka.top/keyu3.php?url=","ext":{"flag":["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"],"header":{"User-Agent":"okhttp/4.1.0"}}},
{"name":"hfys","type":1,"url":"http://119.91.206.244:9999/jx/hfys.php?url=","ext": {"flag": ["duoduozy", "renrenmi","ltnb","miaoparty","miaoparty2","miaoparty3","laodiyun","laodim3u8","lekanzyw","rx","CL4K","fuckapp","1080P", "wuduzy"]}},
{"name": "dygfsdy","type": 1,"url": "http://jx.dygfsdy.com/home/api?type=ys&uid=129415&key=acdmoruwxCDEKPZ679&url=","ext": {"flag": ["qq","腾讯","letv","乐视","mgtv","芒果","youku","优酷","qiyi","iqiyi","爱奇艺","奇艺"]}},
{"name": "anal23","type": 1,"url": "http://39.96.174.234:4433/analysis.php?app=10000&account=SVIP666&password=18123344653&url=","ext": {"flag": ["qiyi","qq","letv","sohu","youku","mgtv","bilibili","wasu","xigua","1905"]}},
{"name": "analysis", "type": 0,"url": "http://42.193.18.62:9999/analysis.php?v=","ext": { "flag": ["qq","腾讯", "qiyi", "爱奇艺","奇艺", "youku", "优酷","mgtv","芒果","letv","乐视","pptv", "PPTV", "sohu","bilibili","哔哩哔哩", "哔哩"]}},          
{"name": "wuyou","type": 0,"url": "http://wuyou.ueuo.com/jx.html?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果"]}},
{"name":"七小时","url":"https://jxxxx.sanmitt.cn/index.php?url="},
{"name":"legen","url": "https://json.legendwhb.cn//llq//?url="},
{"name":"ckplayer","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name": "parwix","type": 0,"url": "https://vip.parwix.com:4433/player/?url=","ext": {"flag": ["ltnb","renrenmi","qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","bilibili","哔哩哔哩","哔哩"]}},
{"name":"17yun","url":"http://www.1717yun.com/api/?url="},
{"name":"扶风","type":1,"url":"https://vip.byteamone.cn/api/?key=iYOnljzBM3qy5y9qZ4&url="},
{"name":"ckmov","url":"https://www.ckmov.vip/api.php?url="},
{"name":"m3u8","url":"https://www.playm3u8.cn/jiexi.php?url="},
{"name":"07u8","url":"https://m3u8.07vod.cn/?url="},
{"name":"17ty","url":"http://www.1717yun.com/jx/ty.php?url="},
{"name":"M117","type":0,"url":"http://1.117.152.239:39000/?url="},
{"name":"M3U8解析","type":0,"url":"https://www.m3u8.tv.cdn.8old.cn/jx.php?url="},
{"name":"bozrc稳定","type":0,"url":"https://jx.bozrc.com:4433/player/?url="},
{"name":"ax","url": "https://api.ax.jx.cn/?url="},
{"name":"zui","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"8090","url":"https://www.8090g.cn/?url="},
{"name":"m3u8tv","url": "http://jx.m3u8.tv/jiexi/?url="},
{"name":"ecsxs","url":"https://wds.ecsxs.com/225173.html?url="},
{"name":"365","url":"https://jx.fulitang365.com/?url="},
{"name":"ltnb","type":0,"url":"https://jx.zui.cm/?url=","ext":{"flag":["ltnb"]}},
{"name":"ml1080","url": "https://www.ml1080.com//mg//?url="},  
{"name":"佳宸","type":0,"url":"http://1link.atwebpages.com/?url="},
{"name":"bl","type":0,"url":"https://svip.bljiex.cc/?v="},
{"name": "rongxing","type": 1,"url": "http://jx.dygfsdy.com/home/api?type=ys&uid=129415&key=acdmoruwxCDEKPZ679&url="},
{"name": "rx","type":1,"url": "https://rx.bt5v.com/json/jsonindex.php/?url="},
{"name": "rxvip","type": 1,"url": "https://vip.rongxingvr.top/api/?key=CwQXkIXGfaUNGVomez&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name": "GGTV你啊","type":1,"url": "https://play.fuqizhishi.com/jx/API.php?appkey=xiaobaiiii&url="},
{"name":"ckplayer","type":0,"url":"https://www.ckplayer.vip/jiexi/?url="},
{"name": "kuanjv","type": 1,"url": "http://rxjx.kuanjv.com/allm3u8.php?url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","搜狐","sohu","letv","乐视","bilibili","哔哩哔哩","哔哩","xigua","西瓜"]}},
//{"name": "GGTV搜集","type": 1,"url": "https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe220902&url="},
{"name":"托乌","type":0,"url":"https://jx.ppjbk.cn/?url="},
{"name":"icu","type":1,"url":"https://cache.json.icu/home/api?type=ys&uid=1362243&key=acfgklqwFLMORSTVZ6&url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905","bilibili","ltnb","renrenmi"]}},
{"name":"kumyun","type":1,"url":"http://www.kumyun.cn/home/api?type=ys&uid=12970&key=eopDJKLMNPSTVXY015&url="},
{"name":"优众","type":1,"url":"http://svip.nfjx.xyz/api/?key=wbbgCgezulNGcZVHc1&url="},
{"name": "无名","type": 1,"url": "https://www.administratorw.com/video.php?url="},
{"name": "爱豆解析","type": 0,"url": "https://jx.aidouer.net/?url="},
{"name":"快速","type":1,"url":"https://play.fuqizhishi.com/juhe/API.php?appkey=caijijuhe&url="},
{"name": "融xing","type": 1,"url": "https://vip.rongxingvr.top/api/?key=DIcBZqAMbKBa1fRdeM&url=","ext": {"flag": ["qq","腾讯","qiyi","爱奇艺","奇艺","youku","优酷","mgtv","芒果","letv","乐视","pptv","PPTV","sohu","bilibili","哔哩哔哩","哔哩"]}},
{"name": "rongxing","type": 1,"url": "https://svip.rongxingvr.top/api/?key=bpWXKrAJUKm3puOCH4&url="},
{"name":"油果","type":1,"url":"http://json.youguo520.top/fufeng/?url=","ext":{"flag":["qiyi","爱奇艺","奇艺","qq","腾讯","youku","优酷","pptv","PPTV","letv","乐视","bilibili","哔哩哔哩","哔哩","mgtv","芒果"],"header":{"User-Agent":"Dart/2.14 (dart:io)"}}}, 
{"name": "beiyan","type": 1,"url": "https://jx.beiyan.cc:4433/?url=","ext": {"flag": ["youku","优酷","mgtv","芒果","qq","腾讯","qiyi","爱奇艺","qq","奇艺"]}},
{"name": "冰豆解析","type": 0,"url": "https://bd.jx.cn/?url="}
],
"flags":["youku","qq","iqiyi","imgo","xueren","m1905","qiyi","letv","sohu","tudou","pptv","dbm3u8","mgtv","wasu","bilibili","le","duoduozy","renrenmi","xigua","优酷","西瓜","乐视","芒果","腾讯","爱奇艺","奇艺","ltnb","rx","CL4K","xfyun","wuduzy","哔哩哔哩","哔哩"],
"ijk":[
{"group":"硬解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"1"},
{"category":4,"name":"mediacodec-auto-rotate","value":"1"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"1"},
{"category":4,"name":"mediacodec-hevc","value":"1"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}
]},
{"group":"软解码","options":[
{"category":4,"name":"opensles","value":"0"},
{"category":4,"name":"overlay-format","value":"842225234"},
{"category":4,"name":"framedrop","value":"1"},
{"category":4,"name":"soundtouch","value":"1"},
{"category":4,"name":"start-on-prepared","value":"1"},
{"category":1,"name":"http-detect-range-support","value":"0"},
{"category":1,"name":"fflags","value":"fastseek"},
{"category":2,"name":"skip_loop_filter","value":"48"},
{"category":4,"name":"reconnect","value":"1"},
{"category":4,"name":"enable-accurate-seek","value":"0"},
{"category":4,"name":"mediacodec","value":"0"},
{"category":4,"name":"mediacodec-auto-rotate","value":"0"},
{"category":4,"name":"mediacodec-handle-resolution-change","value":"0"},
{"category":4,"name":"mediacodec-hevc","value":"0"},
{"category":1,"name":"dns_cache_timeout","value":"600000000"}
]}
],
//"wallpaper": "http://www.kf666888.cn/api/tvbox/img",
"wallpaper":"http://52bsj.vip:82/late",  
"ads":["mimg.0c1q0l.cn","www.googletagmanager.com","www.google-analytics.com","mc.usihnbcq.cn","www.stappupgrade.vivo.com.cn","mg.g1mm3d.cn","www.otheve.beacon.qq.com","mscs.svaeuzh.cn","cnzz.hhttm.top","tp.vinuxhome.com","cnzz.mmstat.com","www.baihuillq.com","s23.cnzz.com","z3.cnzz.com","c.cnzz.com","stj.v1vo.top","z12.cnzz.com","img.mosflower.cn","tips.gamevvip.com","ehwe.yhdtns.com","xdn.cqqc3.com","www.jixunkyy.cn","sp.chemacid.cn","hm.baidu.com","s9.cnzz.com","z6.cnzz.com","um.cavuc.com","mav.mavuz.com","wofwk.aoidf3.com","z5.cnzz.com","xc.hubeijieshikj.cn","tj.tianwenhu.com","xg.gars57.cn","k.jinxiuzhilv.com","cdn.bootcss.com","ppl.xunzhuo123.com","xomk.jiangjunmh.top","img.xunzhuo123.com","z1.cnzz.com","s13.cnzz.com","xg.huataisangao.cn","z7.cnzz.com","xg.huataisangao.cn","z2.cnzz.com","s96.cnzz.com","q11.cnzz.com","thy.dacedsfa.cn","xg.whsbpw.cn","s19.cnzz.com","z8.cnzz.com","s4.cnzz.com","f5w.as12df.top","ae01.alicdn.com","www.92424.cn","k.wudejia.com","vivovip.mmszxc.top","qiu.xixiqiu.com","cdnjs.hnfenxun.com","cms.qdwght.com"]}

